name: local-ai
recipe: drupal11
config:
  webroot: web
  php: "8.3"
  composer_version: '2'
  edge: false
  xdebug: true
services:
  vectordb:
    type: lando
    api: 3
    meUser: root
    portforward: true
    moreHttpPorts:
      - 27017
      - 27018
    internal_connection:
      host: 'vectordb'
      port: 27017
    services:
      user: root
      image: mongodb/mongodb-atlas-local:latest
      command: 'docker-entrypoint.sh mongod'
      privileged: true
      volumes:
        - data:/data/db
      ports:
        - 27018:27017
    healthcheck: "atlas"
    build_as_root:
      - yum install -y mongodb-mongosh
      - yum install -y mongodb-atlas
    run:
      - atlas deployments setup dropai --type local --force
      - mongosh --eval "use default"
  appserver:
    build_as_root:
      - apt-get update -y
      - yes '' | pecl install mongodb
      - docker-php-ext-enable mongodb
    run_as_root:
      - echo "extension=mongodb.so" >> $PHP_INI_DIR/php.ini-production
tooling:
  mongosh:
    service: vectordb
  atlas:
    service: vectordb
