name: local-ai
recipe: drupal11
config:
  webroot: web
  php: "8.3"
  composer_version: '2'
  edge: false
  xdebug: true
services:
  vectordb:
    type: lando
    api: 3
    meUser: root
    port: 27017
    services:
      user: root
      image: mongodb/atlas
      command: mongodb/atlas
      privileged: true
      volumes:
        - data:/data/db
      ports:
        - 27017:27017
    healthcheck: false
    run:
      - atlas deployments setup dropai --type local --force
  appserver:
    build_as_root:
      - apt-get update -y
      - yes '' | pecl install mongodb
      - docker-php-ext-enable mongodb
    run_as_root:
      - echo "extension=mongodb.so" >> $PHP_INI_DIR/php.ini-production
tooling:
  mongosh:
    service: vectordb
  atlas:
    service: vectordb
